export const promptData = [
    {
        id: 1,
        title: 'Hyper-Realistic Cyberpunk Portrait',
        category: 'Midjourney v7 • Cinema Lighting',
        price: '15 Credits',
        reliability: '98% Reliability',
        reliabilityType: 'emerald',
        creator: '@neon_arc',
        creatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCI_hWT5fYXu7wwwHC9jdurg1PjFM4SC4aIj28v_uyC8A2N8G2MKMP46QjtTayMsdIMNNOzYHAb9JSBz3wLIOTctQfwxGmI0aJGmGox4Xu8BNogDDpR7YTXO6vmvXt2rvCaTgpX6U4khnSpRvmrLAAtiTXdjsx9-CPK6pxoUb2daheDm66O5AyRdlmiDNJeH7swkMWrhuETvV29L5vi4trAm_RLSyywrtOk09iZsaRzEX-a9xuwBMOz_EfzDlGnGybgmkR_tUdYwJg',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0gEfY77P8og-t9s-StwLL50G1Kdh_qBP-RXyRh2V3hm5l4M_rCqeDgSYVJK3EqbyEuQlMxAF69HBjmhWJxSR-XyQEENOTir16rTcei3IQn4dGAxGn7QWLFHTXU9exp_az796KuzdNKlOjluXlFkacWLBT1D36MOjmVnMcIDrdyktN52HsUQho69MKXlCb2FAnQaB8s_5tclye_LIYnjaokIGZsXylVvOnbDsBPx9xmpgGdC-7NALHK42h60DgC6wFOdaoV3o1fNo',
        dataAlt: 'Abstract 3D iridescent flowing shapes',
        fullDescription: 'Master the art of high-fidelity cyberpunk portraits with this meticulously engineered prompt structure. Designed specifically for the Midjourney v6 and GPT-4 pipeline, it generates hyper-detailed characters featuring intricate cybernetics, volumetric neon lighting, and cinematic atmospheric effects.',
        verifiedModels: ['MIDJOURNEY 6', 'STABLE DIV XL', 'GPT-4V'],
        sales: '3,492',
        impact: '12.8k'
    },
    {
        id: 2,
        title: 'Minimalist Architectural Render',
        category: 'Stable Diffusion XL • ArchViz',
        price: '12 Credits',
        reliability: '95% Reliability',
        reliabilityType: 'emerald',
        creator: '@archizoom',
        creatorAvatar: null,
        creatorInitials: 'AZ',
        creatorBg: 'bg-primary/20',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCYEC-sCe_gJmifDnY0EaBrToNnVey3Ab9bt46kjYSRJWR01i8Ztn3Nef80uApuD1My_rd2_QW0HXM4v9gWk3LSUHJQnXy4ZCAf59uvaQvFvzE733SJw6qzhbncq3eMoEEfGnJk2XvYfwPaI2f0vQ-rJEBUOh6N00Mn9Xv59YyV4FPs7LhfKZytFE_VhnXrg3BwDEo-TXZY3JQ-CD3W3wkHlUV9tFObTOE0jeQjOIaYUC4UqvhWVYsAAGxaw4f4QrknNhMx1j9Yrj8',
        dataAlt: 'Minimalist modern house at sunset with soft lighting',
        fullDescription: 'Create stunning professional architectural renders with a focus on minimalism and natural light. Perfect for interior designers and architects looking to visualize clean, modern spaces.',
        verifiedModels: ['STABLE DIFFUSION XL', 'LUXCORE', 'DALL-E 3'],
        sales: '1,820',
        impact: '5.4k'
    },
    {
        id: 3,
        title: 'Strategic Business Logic Agent',
        category: 'GPT-5 • Enterprise Operations',
        price: '25 Credits',
        reliability: '100% Reliable',
        reliabilityType: 'blue',
        creator: '@logic_smith',
        creatorAvatar: null,
        creatorIcon: 'smart_toy',
        creatorBg: 'bg-black',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuALrfzOAW8Q4zK5GkcrvbDnTWc4_UwZgVjmgFEQp_srS6qTjyd8JhcvwgjfpuAUZKzUIFqCSY5CZnul2XVbJQ9laMK0bH-2tgjEGNu6gzZLszPnOI7PkZeYJhIreXWivsZWxA3_3023sMjqvDEJv2lm03P7su92XdDa_DWmUacOPoTaMHIUrW3A_29Mq3nQYNNxW74BlN-eOtu2KLgMdKngbcscu8on7EdX2GTgGFfvsWiGXaqPy-f5h7I2RcB81j_fhkIgJO3Lq2U',
        dataAlt: 'Abstract data visualization with complex nodes and connections',
        fullDescription: 'A highly specialized prompt for generating complex business logic and strategic operation plans using GPT-5. Ideal for CTOs and system architects.',
        verifiedModels: ['GPT-5', 'CLAUDE 3.5 SONNET', 'GEMINI 1.5 PRO'],
        sales: '945',
        impact: '22.1k'
    },
    {
        id: 4,
        title: 'Organic Liquid Motion Background',
        category: 'DALL-E 4 • Dynamic Style',
        price: '10 Credits',
        reliability: '92% Reliability',
        reliabilityType: 'emerald',
        creator: '@fluid_master',
        creatorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvRZSLWDavVwIcq5GlOseofZmkO62eJ9rusYAn2NNFwAOoMIYE-1Nq1v8eqQd9EBrHsYMp5QZ7antTAnkw4bTxccogwuBOX1TO0D2-koVoml2FAglDwjfSvthGTd0wqae5e8d1kb7DN1VXhbcem9v0Ae8g9Ven8TE6O-WorFE05IRpwzsGzoXSw1ERB-Ytj_LygHPDaV1nbRlHQENogmgRws9z2YaQapJscJNUiON4En9AmTnJYdnvB32OOMODSQjVpx5MO2vFroY',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDI987ybQdbxwPydnrprUfqA62O7YApVvRSJ7TCft7JoahgzuLRlr-wXCzGOxKM-23bF3DYoXNDtxBqBsbQ16ws1p6UDRj2nlIhnqYh0zxmHfloczbCQWbAQzepllwO4irXJ7SgGMRlKKrWqoyNunVhxXvuoGwhaxzL-9J6qdnlzRh0t4pLWEVO-bzmsocuFqSbO7QWAHJLxiZ7Doh_g7MroooFZpLBRkemaCRNDDKViwfOA0w771JCETACLhpG1oUj6xdRzgfuDCU',
        dataAlt: 'Vibrant multi-colored abstract digital splash',
        fullDescription: 'Generate vibrant, organic motion backgrounds that feel alive. Perfect for landing pages, music videos, and digital art installations.',
        verifiedModels: ['DALL-E 4', 'MIDJOURNEY V6', 'SDXL'],
        sales: '4,102',
        impact: '8.9k'
    },
    {
        id: 5,
        title: '80s Synthwave Sunset Horizon',
        category: 'Midjourney v7 • Retro Style',
        price: '18 Credits',
        reliability: '97% Reliability',
        reliabilityType: 'emerald',
        creator: '@vibe_synth',
        creatorAvatar: null,
        creatorInitials: 'VS',
        creatorBg: 'bg-indigo-500',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwV7lEU31YeJqf1JRMvLTd1v83P6GcfbCIZ3QNAspeTGe5vvBf9xI8TlQO7f92XlaBblJm5yrPBrXAcBd0XuYvuNdBA0D4eZPxLhhRQbggO5nQkyA6XwzE8xIAAjHxy6b-W_UO4j-eXeZDaxEI7CE4nxOWtI3J5AreKOUUfCAm9scqRqqi85NNqZkFMg1AduITxFfUe3uCP9xHf29_jSn4uyH5kqHFC8pK1TKxiERROwblWMjhy92EIkr3O07xmXFW-NZgRdGjtzA',
        dataAlt: 'Retro-futuristic landscape with neon grid lines',
        fullDescription: 'The ultimate retro-future prompt. Generate nostalgic 80s synthwave horizons with neon grids, glowing suns, and perfect VHS aesthetic artifacts.',
        verifiedModels: ['MIDJOURNEY 7', 'STABLE DIFFUSION', 'LEONARDO AI'],
        sales: '2,550',
        impact: '15.2k'
    },
    {
        id: 6,
        title: 'Advanced Python Security Audit Agent',
        category: 'Claude 4 Opus • Software Eng',
        price: '30 Credits',
        reliability: '99% Reliable',
        reliabilityType: 'blue',
        creator: '@dev_guru',
        creatorAvatar: null,
        creatorIcon: 'code',
        creatorBg: 'bg-slate-800',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyw-AFQh5cV4gJ8Bq_BGb4TzktX_Lcy1vjsZYNAN-uRwVOof9ZGYjd3-K-SI4Zwh8L63yckvVAsMNos4zETrgvOWGBzg_ZyYo147vq3ZWLdNJZSNUB0ctArAwU8rJj0bMiIw5p1H7i5qNbbyR4ymU4SXp4HDHnXtspVhcKdYd7OzEd8_BRLysbEnfgnUYfCCtE22q8AvxFnUnmzYO_msGM2BzFoeN8OGrmx094CLVlkm6a5NPYXv8MgeolHf-iQzdHJFqZ-J79Uq4',
        dataAlt: 'Modern dark tech code on a monitor screen',
        fullDescription: 'A master-level prompt for securing Python applications. This agent performs deep static analysis, hunts for SQL injection, and suggests modern security patterns.',
        verifiedModels: ['CLAUDE 4 OPUS', 'GPT-4 TURBO', 'CO-PILOT'],
        sales: '612',
        impact: '4.8k'
    }
];

export const filters = [
    'All Prompts',
    'Photorealistic',
    'Architecture',
    'No-Code Logic',
    'Cyberpunk',
    'Product Design',
    'Abstract Art',
    'Character Design'
];
